spring:
  application:
    name: spring-boot-4-demo
  
  # 配置虚拟线程
  threads:
    virtual:
      enabled: true
  
  # H2数据库配置
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console

# 服务器配置
server:
  port: 8080
  shutdown: graceful

# Actuator配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans,threadump
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: true

# 日志配置
logging:
  level:
    com.example.demo: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"